version: "3.9"
services:
  app:
    image: "web_files_app:dev"
    build:
      context: .
      dockerfile: ./dockers/app/Dockerfile
      args:
        USER_ID: ${USER_ID}
        USER_NAME: dev
    user: "${USER_ID}:${USER_ID}"
    ports:
      - 5000:5000
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_WEB_FILES_SITE_TITLE: Web File Manager
      FLASK_WEB_FILES_WEB_ROOT: /var/www
      FLASK_WEB_FILES_DOMAIN_ROOT: http://localhost:5001
      FLASK_SECRET_KEY: "Som3th1ng |2eally SSSecret"
    command: python -m flask run --host=0.0.0.0
    volumes:
      - .:/app
      - ./test/data/web_root:/var/www
  web:
    image: "nginx:stable-alpine"
    ports:
      - 5001:80
    volumes:
      - ./test/data/web_root:/usr/share/nginx/html
